twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/src/FrontEndBundle/Resources/views': FrontEndBundle

when@test:
    twig:
        strict_variables: true
