#index:
#    path: /
#    controller: App\Controller\DefaultController::index


BackendBundle:
  resource: "@BackendBundle/Controller/"
  type: annotation
  prefix: /api

FrontEndBundle:
  resource: "@FrontEndBundle/Controller/"
  type: annotation
  prefix: /