services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\FrontEndBundle\:
    resource: '%kernel.project_dir%/src/FrontEndBundle/'
    exclude:
      - '%kernel.project_dir%/src/FrontEndBundle/DependencyInjection/'
      - '%kernel.project_dir%/src/FrontEndBundle/Entity/'
      - '%kernel.project_dir%/src/Kernel.php'
      - '%kernel.project_dir%/src/FrontEndBundle/Tests/'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones